### PR TITLE
Move Janrain to inactive

### PR DESCRIPTION
**Pull request by mboes**
It got acquired earlier this year.

### CODE REVIEW

**Comment by sigrlami** [comment]
Agree but that means Akamai now uses Haskell? Or there no confirmations?

**Comment by sigrlami** [comment]
Also, @mboes take a look at https://haskellcosm.com/analysis.html (if you're on a desktop) this based out on structured raw data, lacks legend as of now, but maybe you'll find it entertaining.

**Comment by mboes** [comment]
Oh, very cool!

Re Akamai: I have no idea. The fact that Janrain got acquired is just
something I noticed on Wikipedia.

**Comment by sigrlami** [comment]
Thanks for the hint. No public records of using Haskell by Akamai even after acquisition of Janrain.

**Pull request merged**
